/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_c6a3dee9 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/zwbrhjofdggfjwsalrqt/database/tables

// @deno-types="npm:@supabase/supabase-js@2.49.8"
import { createClient } from "npm:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c6a3dee9").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c6a3dee9").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c6a3dee9").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// mset stores multiple key-value pairs at once
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client();
  const records = keys.map((key, idx) => ({
    key,
    value: values[idx]
  }));
  
  const { error } = await supabase.from("kv_store_c6a3dee9").upsert(records);
  if (error) {
    throw new Error(error.message);
  }
};

// getByPrefix retrieves all key-value pairs with a given prefix
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_c6a3dee9")
    .select("value")
    .ilike("key", `${prefix}%`);
  
  if (error) {
    throw new Error(error.message);
  }
  
  return data?.map((item: any) => item.value) || [];
};